/**
 * CLAW-145 public skill browse taxonomy (15 fixed categories).
 * "other" is internal-only — not listed here.
 */
export const BROWSE_TAXONOMY_DEFINITIONS = [
  {
    slug: "data-apis",
    label: "Data, APIs & Integrations",
    keywords: [
      "api",
      "apis",
      "data",
      "fetch",
      "http",
      "rest",
      "graphql",
      "integrate",
      "integration",
      "reconcile",
      "records",
      "services",
      "brave",
      "search",
      "clawdhub",
      "healthkit",
      "sync",
      "model",
      "usage",
    ],
    boundary:
      "Connect services, fetch data, reconcile records, or operate APIs.",
    examples: ["brave-search", "clawdhub", "model-usage", "healthkit-sync"],
    heuristicMatches: 10580,
  },
  {
    slug: "agent-behavior",
    label: "Agent Behavior & Memory",
    keywords: [
      "agent",
      "behavior",
      "memory",
      "plan",
      "planning",
      "reflect",
      "learning",
      "collaborate",
      "improving",
      "paprika",
      "tachograph",
      "triage",
      "root",
      "cause",
    ],
    boundary:
      "Change how an agent plans, reflects, learns, remembers, or collaborates.",
    examples: [
      "self-improving-agent",
      "paprika",
      "self-improving-agent-1-0-0",
      "tachograph-infringement-triage-root-cause-uk",
    ],
    heuristicMatches: 7832,
  },
  {
    slug: "media-creative",
    label: "Media & Creative",
    keywords: [
      "media",
      "creative",
      "image",
      "video",
      "audio",
      "music",
      "design",
      "writing",
      "generation",
      "editing",
      "transcribe",
      "songsee",
      "table",
      "podcast",
    ],
    boundary:
      "Image, video, audio, music, design, writing, generation, and editing.",
    examples: ["songsee", "openrouter-transcribe", "table-image", "pocket-casts-yt"],
    heuristicMatches: 7630,
  },
  {
    slug: "automation-workflows",
    label: "Automation & Workflows",
    keywords: [
      "automation",
      "workflow",
      "workflows",
      "schedule",
      "scheduled",
      "cron",
      "pipeline",
      "orchestration",
      "repeatable",
      "process",
      "accli",
      "jira",
      "bambu",
      "team",
    ],
    boundary: "Repeatable processes, scheduled jobs, pipelines, and orchestration.",
    examples: ["accli", "claude-team", "jira", "bambu-cli"],
    heuristicMatches: 5230,
  },
  {
    slug: "finance-commerce",
    label: "Finance, Commerce & Crypto",
    keywords: [
      "finance",
      "financial",
      "payment",
      "payments",
      "budget",
      "budgeting",
      "banking",
      "subscription",
      "shopping",
      "market",
      "markets",
      "crypto",
      "stock",
      "ynab",
      "yahoo",
      "analysis",
    ],
    boundary:
      "Payments, budgeting, banking, subscriptions, shopping, markets, and crypto.",
    examples: ["gno", "ynab", "yahoo-finance", "stock-analysis"],
    heuristicMatches: 4909,
  },
  {
    slug: "web-research",
    label: "Web, Browser & Research",
    keywords: [
      "web",
      "browser",
      "browse",
      "scrape",
      "scraping",
      "research",
      "summarize",
      "monitor",
      "extract",
      "blog",
      "watcher",
      "places",
      "local",
    ],
    boundary: "Search, browse, scrape, summarize, monitor, or extract web info.",
    examples: ["blogwatcher", "brave-search", "local-places"],
    heuristicMatches: 3319,
  },
  {
    slug: "docs-knowledge",
    label: "Docs, Knowledge & Notes",
    keywords: [
      "docs",
      "document",
      "documents",
      "pdf",
      "note",
      "notes",
      "knowledge",
      "obsidian",
      "bear",
      "apple",
      "store",
    ],
    boundary: "Work with docs, PDFs, notes, knowledge bases, and memory stores.",
    examples: ["apple-notes", "bear-notes", "obsidian"],
    heuristicMatches: 2982,
  },
  {
    slug: "dev-tools",
    label: "Coding & Dev Tools",
    keywords: [
      "dev",
      "code",
      "coding",
      "debug",
      "lint",
      "test",
      "build",
      "github",
      "frontend",
      "packaging",
      "spm",
      "macos",
      "inspect",
      "edit",
      "operate",
      "codebase",
    ],
    boundary: "Inspect, edit, test, build, debug, or operate codebases.",
    examples: ["github", "claude-team", "macos-spm-app-packaging", "frontend-design-1-0-0"],
    heuristicMatches: 2694,
  },
  {
    slug: "communication-social",
    label: "Communication & Social",
    keywords: [
      "communication",
      "messaging",
      "message",
      "social",
      "discord",
      "slack",
      "posting",
      "publish",
      "mail",
      "beeper",
      "yoinkit",
      "networks",
    ],
    boundary:
      "Messaging, posting, social networks, Discord, Slack, and publishing.",
    examples: ["slack", "beeper", "apple-mail-search-safe", "yoinkit"],
    heuristicMatches: 2674,
  },
  {
    slug: "monitoring-ops",
    label: "Monitoring & Ops",
    keywords: [
      "monitoring",
      "monitor",
      "observability",
      "deployment",
      "deployments",
      "logs",
      "alerts",
      "diagnostic",
      "diagnostics",
      "status",
      "trimet",
      "virus",
    ],
    boundary: "Status checks, observability, deployments, logs, alerts, and diagnostics.",
    examples: ["claude-team", "trimet", "bambu-cli", "virus-monitor"],
    heuristicMatches: 2592,
  },
  {
    slug: "productivity-tasks",
    label: "Productivity & Tasks",
    keywords: [
      "productivity",
      "task",
      "tasks",
      "calendar",
      "email",
      "planning",
      "todoist",
      "things",
      "gog",
      "manager",
      "management",
    ],
    boundary: "Task managers, calendars, email, planning, and lightweight work management.",
    examples: ["todoist-cli", "gog", "things-mac", "accli"],
    heuristicMatches: 2419,
  },
  {
    slug: "security-review",
    label: "Security, Vetting & Trust",
    keywords: [
      "security",
      "audit",
      "auditing",
      "vetting",
      "vulnerability",
      "malware",
      "secret",
      "secrets",
      "scanner",
      "scan",
      "trust",
      "openssl",
      "password",
      "securevibes",
    ],
    boundary:
      "Security-focused auditing, vetting, vulnerability scanning, malware/secret detection, trust checks, and artifact risk review.",
    examples: ["1password", "openssl", "securevibes-scanner", "lark-custom-bot"],
    heuristicMatches: 1855,
  },
  {
    slug: "education-learning",
    label: "Education & Learning",
    keywords: [
      "education",
      "learning",
      "tutor",
      "tutoring",
      "study",
      "exercise",
      "exercises",
      "explain",
      "language",
      "practice",
      "streaming",
      "buddy",
      "alephnet",
      "moltmarkets",
    ],
    boundary: "Tutoring, study, exercises, explanations, language learning, and practice.",
    examples: [
      "streaming-buddy",
      "alephnet-node",
      "moltmarkets-agent",
      "moltmarkets-trading",
    ],
    heuristicMatches: 1473,
  },
  {
    slug: "local-system",
    label: "Local System & Files",
    keywords: [
      "filesystem",
      "desktop",
      "shell",
      "device",
      "devices",
      "backup",
      "backups",
      "local",
      "dyson",
      "heypocket",
      "reader",
      "apple",
      "notes",
      "operate",
      "state",
    ],
    boundary:
      "Operate the local OS, desktop apps, filesystem, shell sessions, devices, backups, or local state.",
    examples: ["apple-notes", "dyson-cli", "heypocket-reader"],
    heuristicMatches: 835,
  },
  {
    slug: "domain-utilities",
    label: "Domain Utilities",
    keywords: [
      "domain",
      "utility",
      "utilities",
      "specialized",
      "fitbit",
      "whatdo",
      "gevety",
      "oebb",
      "scotty",
    ],
    boundary: "Specialized helpers that may stay domain-specific or collapse later.",
    examples: ["fitbit", "whatdo", "gevety", "oebb-scotty"],
    heuristicMatches: 326,
  },
] as const;

export type BrowseTaxonomySlug = (typeof BROWSE_TAXONOMY_DEFINITIONS)[number]["slug"];

export const BROWSE_TAXONOMY_SERVER_CATEGORIES = BROWSE_TAXONOMY_DEFINITIONS.map(
  ({ slug, keywords }) => ({ slug, keywords: [...keywords] }),
);

export const BROWSE_TAXONOMY_PUBLIC_SLUGS = new Set<string>(
  BROWSE_TAXONOMY_DEFINITIONS.map((category) => category.slug),
);

export function getBrowseTaxonomyCategory(slug: string) {
  return BROWSE_TAXONOMY_DEFINITIONS.find((category) => category.slug === slug);
}

export function isBrowseTaxonomySlug(slug: string): slug is BrowseTaxonomySlug {
  return BROWSE_TAXONOMY_PUBLIC_SLUGS.has(slug);
}
